# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from queue import Queue
from threading import Thread
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QObject, pyqtSignal, QTimer
from clientcls import Client


class OutputLogger(QObject):
    emit_write = pyqtSignal(str, int)

    class Severity:
        DEBUG = 0
        ERROR = 1

    def __init__(self, io_stream, severity):
        super().__init__()

        self.io_stream = io_stream
        self.severity = severity

    def write(self, text):
        self.io_stream.write(text)
        self.emit_write.emit(text, self.severity)

    def flush(self):
        self.io_stream.flush()


OUTPUT_LOGGER_STDOUT = OutputLogger(sys.stdout, OutputLogger.Severity.DEBUG)
OUTPUT_LOGGER_STDERR = OutputLogger(sys.stderr, OutputLogger.Severity.ERROR)

sys.stdout = OUTPUT_LOGGER_STDOUT
sys.stderr = OUTPUT_LOGGER_STDERR


class UiMainWindow(object):
    def __init__(self, main_window):
        super().__init__()
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.massage_block = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.message = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.send = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.list_contact_view = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.contact_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.contact_view = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.update_contact = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.list_local_contact_view = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3
        )
        self.contact_local_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.contact_local_view = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.update_contact_local = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.chat = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.chat_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chat_view = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.connect = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.connect_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ip_block = QtWidgets.QHBoxLayout()
        self.ip_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.ip_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.tcp_block = QtWidgets.QHBoxLayout()
        self.tcp_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.tcp_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.res_queue = Queue()
        OUTPUT_LOGGER_STDOUT.emit_write.connect(self.append_log)
        OUTPUT_LOGGER_STDERR.emit_write.connect(self.append_log)

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(800, 620)
        main_window.setStyleSheet("background-color : rgb(114, 159, 207)")

        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 529, 591, 72))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.massage_block.setContentsMargins(0, 0, 0, 0)
        self.massage_block.setObjectName("massage_block")
        self.message.setMaximumSize(QtCore.QSize(500, 16777215))
        self.message.setStyleSheet("background-color: white")
        self.message.setObjectName("message")
        self.massage_block.addWidget(self.message)
        self.send.setEnabled(True)
        self.send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.send.setAutoDefault(False)
        self.send.setDefault(True)
        self.send.setObjectName("send")
        self.massage_block.addWidget(self.send)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 160, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.list_contact_view.setContentsMargins(0, 0, 0, 0)
        self.list_contact_view.setObjectName("list_contact_view")
        self.contact_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_label.setObjectName("contact_label")
        self.list_contact_view.addWidget(self.contact_label)
        self.contact_view.setStyleSheet("background-color: white")
        self.contact_view.setObjectName("contact_view")
        self.list_contact_view.addWidget(self.contact_view)
        self.update_contact.setObjectName("update_contact")
        self.list_contact_view.addWidget(self.update_contact)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 320, 160, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.list_local_contact_view.setContentsMargins(0, 0, 0, 0)
        self.list_local_contact_view.setObjectName("list_local_contact_view")
        self.contact_local_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_local_label.setObjectName("contact_local_label")
        self.list_local_contact_view.addWidget(self.contact_local_label)
        self.contact_local_view.setStyleSheet("background-color: white")
        self.contact_local_view.setObjectName("contact_local_view")
        self.list_local_contact_view.addWidget(self.contact_local_view)
        self.update_contact_local.setObjectName("update_contact_local")
        self.list_local_contact_view.addWidget(self.update_contact_local)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 64, 591, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.chat.setContentsMargins(0, 0, 0, 0)
        self.chat.setObjectName("chat")
        self.chat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chat_label.setObjectName("chat_label")
        self.chat.addWidget(self.chat_label)
        self.chat_view.setStyleSheet("background-color: white")
        self.chat_view.setObjectName("chat_view")
        self.chat.addWidget(self.chat_view)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 19, 591, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.connect.setContentsMargins(0, 0, 0, 0)
        self.connect.setObjectName("connect")
        self.connect_btn.setObjectName("connect_btn")
        self.connect.addWidget(self.connect_btn)
        self.ip_block.setObjectName("ip_block")
        self.ip_label.setStyleSheet("border: 4px double black;")
        self.ip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_label.setObjectName("ip_label")
        self.ip_block.addWidget(self.ip_label)
        self.ip_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ip_edit.setAutoFillBackground(False)
        self.ip_edit.setStyleSheet("background-color: white")
        self.ip_edit.setText("127.0.0.1")
        self.ip_edit.setObjectName("ip_edit")
        self.ip_block.addWidget(self.ip_edit)
        self.connect.addLayout(self.ip_block)
        self.tcp_block.setObjectName("tcp_block")
        self.tcp_label.setStyleSheet("border: 4px double black;")
        self.tcp_label.setScaledContents(False)
        self.tcp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tcp_label.setWordWrap(False)
        self.tcp_label.setObjectName("tcp_label")
        self.tcp_block.addWidget(self.tcp_label)
        self.tcp_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tcp_edit.setAutoFillBackground(False)
        self.tcp_edit.setStyleSheet("background-color: white")
        self.tcp_edit.setText("7777")
        self.tcp_edit.setObjectName("tcp_edit")
        self.tcp_block.addWidget(self.tcp_edit)
        self.connect.addLayout(self.tcp_block)
        main_window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(main_window)
        self.connect_btn.clicked.connect(self.client_click)
        self.send.clicked.connect(self.terminal_answer)
        self.update_contact.clicked.connect(self.send_k)
        self.update_contact_local.clicked.connect(self.send_p)
        self.contact_view.itemDoubleClicked.connect(self.change_user)
        self.contact_local_view.itemDoubleClicked.connect(self.add_contact)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def append_log(self, text, severity):
        text = text

        if severity == OutputLogger.Severity.ERROR:
            text = f"<b>{text}</b>"

        self.chat_view.append(text)

    def terminal_answer(self):
        text = self.message.toPlainText()
        self.res_queue.put(text)

    def change_user(self, item):
        self.res_queue.put("П")
        self.res_queue.put(item.text())

    def send_k(self):
        self.res_queue.put("К")
        QTimer.singleShot(200, self.view_contacts)

    def view_contacts(self):
        self.contact_view.clear()
        list_contact = self.res_queue.get()
        self.contact_view.addItems(list_contact)

    def send_p(self):
        self.res_queue.put("А")
        QTimer.singleShot(200, self.view_local_contacts)

    def add_contact(self, item):
        self.res_queue.put("П")
        self.res_queue.put(item.text())
        self.res_queue.put("")

    def view_local_contacts(self):
        self.contact_local_view.clear()
        list_contact = self.res_queue.get()
        try:
            self.contact_local_view.addItems(list_contact)
        except TypeError:
            pass

    def client_click(self):
        a = self.ip_edit.text()
        b = self.tcp_edit.text()
        self.chat_view.clear()
        if a != "" and b.isdigit():
            self.chat_view.setText("Подключение удалось.")
            con = Client(a, int(b), res_queue=self.res_queue)
            server_proc = Thread(target=con.client_original)
            server_proc.daemon = True
            server_proc.start()
        else:
            self.chat_view.setText("Подключение не удалось")

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send.setText(_translate("MainWindow", "Отправить"))
        self.contact_label.setText(
            _translate("MainWindow", "Список ваших\n" "контактов")
        )
        self.update_contact.setText(_translate("MainWindow", "Обновить"))
        self.contact_local_label.setText(
            _translate("MainWindow", "Список локальных\n" "контактов")
        )
        self.update_contact_local.setText(_translate("MainWindow", "Обновить"))
        self.chat_label.setText(_translate("MainWindow", "ЧАТ"))
        self.connect_btn.setText(_translate("MainWindow", "Подключение к чату"))
        self.ip_label.setText(_translate("MainWindow", "IP"))
        self.tcp_label.setText(_translate("MainWindow", "TCP"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = UiMainWindow(window)
    ui.setup_ui(window)
    window.show()
    sys.exit(app.exec_())
